Repository DeNA/Anjin, pull requests merged in 2023-11, with the labels that each got.

#10 Fix test asset name
  Tests/TestAssets/DoNothingAgentForTests.asset
Labels: bug

#18 Make be able to implement custom composite agents
  Runtime/Agents/AbstractAgent.cs
  Runtime/Agents/AbstractCompositeAgent.cs
Labels: enhancement

#17 Update test-helper.monkey
  Editor/DeNA.Anjin.Editor.asmdef
  Editor/Localization/ja.po
  Editor/UI/Agents/UGUIMonkeyAgentEditor.cs
  README.md
  README_ja.md
  Runtime/Agents/UGUIMonkeyAgent.cs
  Runtime/DeNA.Anjin.asmdef
  package.json
Labels: enhancement

#20 Fix not stopping and reporting when error occurred
  Editor/DeNA.Anjin.Editor.asmdef
  Editor/UI/Settings/AutopilotSettingsEditor.cs
  Runtime/AgentDispatcher.cs
  Runtime/Autopilot.cs
  Runtime/Utilities/LogMessageHandler.cs
  Tests/Runtime/LauncherTest.cs
  Tests/Runtime/TestDoubles/StubClickAgent.cs
  Tests/Runtime/TestDoubles/StubClickAgent.cs.meta
  Tests/Runtime/TestDoubles/StubThrowingErrorOnClick.cs
  Tests/Runtime/TestDoubles/StubThrowingErrorOnClick.cs.meta
  Tests/TestAssets/AutopilotSettingsForFacingImmediatelyError.asset
  Tests/TestAssets/AutopilotSettingsForFacingImmediatelyError.asset.meta
  Tests/TestAssets/StubClickAgentForTests.asset
  Tests/TestAssets/StubClickAgentForTests.asset.meta
  Tests/TestAssets/StubImmediatelyErrorAgentForTests.asset
  Tests/TestAssets/StubImmediatelyErrorAgentForTests.asset.meta
  Tests/TestScenes/Error.unity
  Tests/TestScenes/Error.unity.meta
Labels: bug

#21 Fix not reported when log from not main thread
  Runtime/Autopilot.cs
  Runtime/Utilities/LogMessageHandler.cs
  Tests/Runtime/TestDoubles/StubThrowingErrorFromNotMainThreadOnClick.cs
  Tests/Runtime/TestDoubles/StubThrowingErrorFromNotMainThreadOnClick.cs.meta
  Tests/TestAssets/StubClickAgentForTests.asset
  Tests/TestScenes/Error.unity
Labels: bug

#24 Fix for older Unity
  Runtime/Reporters/SlackReporter.cs
  Tests/Runtime/TestDoubles/StubClickAgent.cs
Labels: fix
