Repository DeNA/Anjin, pull requests merged in 2023-04, with the labels that each got.

#9 Change pr-labeler workflow trigger to pull_request_target
  .github/workflows/pr-labeler.yml
Labels: chore

#8 Fix typo s/dom.dena/com.dena/
  README.md
  README_ja.md
Labels: bug

#14 Add troubleshooting about using UniTask 2.3.0 or older case
  README.md
  README_ja.md
Labels: chore

#13 forgot to call Apply on the texture copy of the screenshot
  Runtime/Reporters/SlackReporter.cs
Labels: feature
